// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTYsfMd49IIhFw8EZDpQ6Bu5YgQO0LVkk',
    appId: '1:380596777634:web:0035fe106bce326b339dfb',
    messagingSenderId: '380596777634',
    projectId: 'fir-671a4',
    authDomain: 'fir-671a4.firebaseapp.com',
    storageBucket: 'fir-671a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOUm9VF2L9MbMeCKFq8cXGSohMOONTeDI',
    appId: '1:380596777634:android:2c554c0a9ad4ddda339dfb',
    messagingSenderId: '380596777634',
    projectId: 'fir-671a4',
    storageBucket: 'fir-671a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkWiEF8gOpaQQ05730_iBONKeZUnuxs8I',
    appId: '1:380596777634:ios:1741c75e7e9fe3a2339dfb',
    messagingSenderId: '380596777634',
    projectId: 'fir-671a4',
    storageBucket: 'fir-671a4.firebasestorage.app',
    iosClientId: '380596777634-lhkepq4hiq5pfa0oet26u06lk61usl0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkWiEF8gOpaQQ05730_iBONKeZUnuxs8I',
    appId: '1:380596777634:ios:1741c75e7e9fe3a2339dfb',
    messagingSenderId: '380596777634',
    projectId: 'fir-671a4',
    storageBucket: 'fir-671a4.firebasestorage.app',
    iosClientId: '380596777634-lhkepq4hiq5pfa0oet26u06lk61usl0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTYsfMd49IIhFw8EZDpQ6Bu5YgQO0LVkk',
    appId: '1:380596777634:web:4028dbb1427bdd75339dfb',
    messagingSenderId: '380596777634',
    projectId: 'fir-671a4',
    authDomain: 'fir-671a4.firebaseapp.com',
    storageBucket: 'fir-671a4.firebasestorage.app',
  );
}
